services:
  db:
    image: postgres:15
    container_name: chitchat_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chitchat_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chitchat_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app # Mount the local backend directory to /app in the container
      - /app/node_modules # Prevent overwriting of node_modules in the container

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Access pgAdmin at localhost:5050
    depends_on:
      - db

volumes:
  db_data:
